# Generated by Django 5.1 on 2024-08-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('superuser', models.BooleanField(default=False, verbose_name='Super User')),
                ('active', models.BooleanField(default=True, verbose_name='Activated')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Join')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Delete')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
