version: '3'
services:
  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5438:5432

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: mycase-rabbitmq
    env_file:
      - .env
    ports:
      - "15672:15672" # RabbitMQ management port

  web:
    build: .
    image: mycase-web
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq

volumes:
  postgres_data: